version: '3.8'
services:
  comictoon-portal-database:
    container_name: comictoon-postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: comictoon
      POSTGRES_USER: comictoon
      POSTGRES_DB: comictoon-local
    ports:
      - 54321:5432
    volumes:
      - ./comictoon-db-data:/var/lib/postgresql/data

  pgadmin4:
    container_name: comictoon-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: comictoon@admin.com
      PGADMIN_DEFAULT_PASSWORD: comictoon
    ports:
      - 5050:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  redis:
    container_name: toon-redis
    image: redis:7.0
    ports:
      - 6379:6379

  redis-commander:
    container_name: toon-redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  comictoon-db-data:
  pgadmin-data: